### Send POST request with json body
POST http://localhost:9090/auth/register
Content-Type: application/json

{
  "full_name": "John Doe",
  "phone": "1234567890",
  "email": "johndoe@example.com",
  "username": "johndoe123",
  "password": "password123"
}
